### PR TITLE
Rework Keyboard code.

### PR DESCRIPTION
**Pull request by mateon1**
Hey, "Antimony" here.
While I tested the keyboard system in separation (and it worked), I wasn't
able to test the whole application, but it should work.

I also made a modification, allowing multiple of the same keyboard command
to be queued. (this should help with Swipe typing)

### CODE REVIEW

**Comment by cnlohr** [comment]
I hope to test this tonight.

**Comment by cnlohr** [comment]
Hmm.. swipe is definitely not working.  Sometimes it skips over letter, etc.  But! You got delete working.  I still need to figure out how to do [enter] but I can do that later.  For now this is good to go.

**Comment by mateon1** [comment]
I believe the swipe thing is an issue with the system not polling the arduino often enough, not sure if you can add any form of delay there, either before the websocket or on the arduino itself.

**Comment by mateon1** [comment]
Sorry, not arduino, but the ESP. I work way too much on an arduino :)

**Comment by cnlohr** [comment]
Ah! Yes, that would explain it.  I had to add the interval thing to make sure it gave a good chunk of wait before the next event happening.

**Pull request merged**
